export enum EnumBanks {
    ITAU = "ITAU",
    BRADESCO = "BRADESCO",
    SANTANDER = "SANTANDER",
    CAIXA = "CAIXA",
    HSBC = "HSBC",
    CITI = "CITI",
    BCO = "BCO",
    BANCO_DO_BRASIL = "BANCO_DO_BRASIL",
    NUBANK = "NUBANK",
    INTER = "INTER",
    WILLBANK = "WILLBANK",
    PICPAY = "PICPAY",
    C6BANK = "C6BANK",
    BTG_PACTUAL = "BTG_PACTUAL",
    JP_MORGAN = "JP_MORGAN"
}
